### PR TITLE
update footer links

### PR DESCRIPTION
**Pull request by Nsl106**

### CODE REVIEW

**Comment by nathana10988** [comment]
I think we should wait for the team page and sponsor page

**Comment by emster1225** [comment]
Looks good to me!

**Comment by emster1225** [comment]
> I think we should wait for the team page and sponsor page

Is it easier to do one update all at once?

**Comment by nathana10988** [comment]
> > I think we should wait for the team page and sponsor page
> 
> Is it easier to do one update all at once?

Or we can just change it in each page because they're not merged yet

**Comment by Nsl106** [comment]
Yeah, I'll do that

**Pull request merged**
